### PR TITLE
Reimplementation of Chisel De-molding

### PR DESCRIPTION
**Pull request by Nyxane**
Removed the woodencog:deployer recipes as those don't have fire_mold variants or support additional casting recipes

With this reimplementation, it will be based on all of tfc:casting recipes, so any future tfc:casting recipes will automatically be added

Note: currently doesn't support TFC Channels and Casting's food casting (No idea how to)

### CODE REVIEW

**Review by pietro-lopes — CHANGES_REQUESTED** [review]
Comparing woodencog with this implementation I'm seeing that this one doesn't have the max temperature stuff.
Is it intended to be able to pop the item from yet molten/too hot molds?

**Comment by Nyxane** [comment]
Changes have been made to respect melting temperature

**Review by pietro-lopes — APPROVED** [review]

**Comment by Nyxane** [comment]
Strange bug where the script doesn't work on server startup found, working on a fix, but unlikely as it seems the metal registry from TFC is empty when the script is ran

**Comment by Nyxane** [comment]
Removed max_temp as Metal registry isn't available at the time its ran

**Review by thevortex — APPROVED** [review]

**Pull request merged**
