### PR TITLE
Update createAdd.js

### PR DESCRIPTION
**Pull request by Angel-Abaddon**
added recipes from firmalife's mixing bowl to create mixer. also added a recipe fix for cocoa powder / cocoa butter as they originally had the same recipes and coca powder was uncraftable

### CODE REVIEW

**Comment by thevortex** [comment]
cool tysm!

**Comment by pietro-lopes** [comment]
@thevortex there are a few of items on the input that are with the not_rotten type, also Cocoa recipe is not broken.

**Comment by Angel-Abaddon** [comment]
> @thevortex there are a few of items on the input that are NOT with the not_rotten type, also Cocoa recipe is not broken.

ah! your right, they aren't broken. i saw the same recipe in jei and when i tested i had a full inventory and didn't notice i was getting both. i shall remove them and i'll add the not_rotten types, my bad

**Comment by pietro-lopes** [comment]
you should also suggest this to Woodencog dev
[Woodencog topic on TFC Discord](https://discord.com/channels/432522930610765835/1086013583407718552)

**Comment by Angel-Abaddon** [comment]
@pietro-lopes I'm sorry for my ignorance (and my rotten mistake) but could you advise how to make the changes? now that its been merged do i have to make a new pull request? I'm new to github ...and mod packs in general, i just did this for myself in the first place, just wanted to share lol

**Comment by pietro-lopes** [comment]
> @pietro-lopes I'm sorry for my ignorance (and my rotten mistake) but could you advise how to make the changes? now that its been merged do i have to make a new pull request? I'm new to github ...and mod packs in general, i just did this for myself in the first place, just wanted to share lol

Yes, you need to resync your fork, do your changes and send a new PR.

**Pull request merged**
