### PR TITLE
Changed the storage drawer upgrade recipes

### PR DESCRIPTION
**Pull request by Nyxane**
Note: I added a ULV craft for the one stack upgrade, I was planning to remove the default one but im not sure if ULV is the right recipe, I left both recipes in for now

### CODE REVIEW

**Comment by Hjaldar** [comment]
I think this is a misguided change (see end for an alternate suggestion), particularly given the small stack sizes of some items and how expensive circuits are, particularly early on. I'd rather use circuits to build infrastructure. Which means I will just end up spamming extra drawers, which is bad QoL and bad for performance. Here are some practical examples based up on my actual playthrough partway through LV:

1. Tin. I have 2.3k tin ingots because it often comes with copper, which you need a lot of in LV. An un-upgraded draw holds 512 tin. I have a choice here between using 5 drawers to hold my tin or using 6 LV circuits to be able to hold just my tin in a single draw.
2. Chromite. I have 1.2k rich because it is everywhere when mining. 3 drawers or 4 LV circuits.
3. Purified Bentonite. I've been using Bentonite as my main first source of Aluminium for when I progress to MV. I now have 600 Aluminium ingots (2 drawers or 2 LV circuits in one drawer) and 1.7k purified Bentonite (2 drawers or 2 LV circuits) which I will process later when it is more efficient.
4. There are many more examples I could list but I'm sure you get the idea.

As an alternative I'd suggest replacing the ingots to something GT-tier appropriate.
Obsidian -> Cast Iron
Iron -> Steel
Gold -> Stainless Steel
Diamond -> Tungstensteel
Emerald -> ???

**Comment by Nyxane** [comment]
The main idea here is to balance it around TFC, with the numbers you provided this enforces the idea its well balanced IMO. Its already strange you can walk around carrying 32 stacks of anything and/or everything in a single slot. storage drawers are not supposed to be the go to "backpack" for single items, inventory management is part of the pack

`I'd rather use circuits to build infrastructure`
This is really bugging me, are drawers not considered infrastructure?

the problems with making upgrades too cheap is due to the fact that you can just storage controller a practically infinite amount of drawers, on top of being able to stack multiple upgrades into 1 drawer.

If you need bigger storage, there is the Super/Quantum Chests that are available with the same type of circuits and extra resources, which have vastly dense storage ie. Super Chest 1 allows for 8 000 000 items, the downside here is that they can't be upgraded nor can they be attached to a Storage controller (afaik)

I'm not trying to make Storage Drawers the best or the worst, its supposed to be balanced around any other option available so that the player can have the choice between them rather than just going for... Storage Drawer only and best path

If you could suggest something that doesn't appear too frequently like GT ingots, but not too rare, I'll gladly consider if its a viable option.

**Comment by Gaelmare** [comment]
Yeah, I don't get balancing storage around TFC when Gregtech is involved and adds many thousands of items plus all the other mods creating unique items in this pack. Storage drawers are already awful for one-off items, and even though we're in HV, our best storage solution is a massive amount of storage drawers and controller, and an ID connection to 20 or so aluminum crates for books, scrolls, etc. We have many upgrades, and are constantly making more. Someone on the team dumped 16k brown sand in the ID system, and then all the honey frames, random plants, and apotheosis drops started filling drawers.

Gating drawer upgrades on circuits is a bad idea.

**Comment by thevortex** [comment]
> 
> Gating drawer upgrades on circuits is a bad idea.

i do feel that the base drawer upgrades are cheaper than they maybe should be, i haven't merged this yet as I was wanting to see this inevitable discussion play out, is there a middle ground that would feel balanced or are you saying that they are good where they are?

**Comment by Gaelmare** [comment]
I agree they're too cheap. I would map them as follows, assuming HV is when ID becomes widely available:

Obby: Bronze plates
Iron: Iron plates
Gold: Steel plates
Diamond: Aluminum plates
Emerald: Stainless steel plates

**Comment by Hjaldar** [comment]
I agree they are also too cheap currently. I found a lot of gold from early exploring, so 8x upgrades were effectively free. However, make them too expensive and players will just craft a second draw rather than upgrading an existing drawer.

Gaelmare's suggestions make sense and I like that they use plates which get cheaper over time with better machines.

**Comment by Nyxane** [comment]
How does 4 plates per upgrade sound?

Obby: Bronze
Iron: Wrought Iron
Gold: Steel
Diamond: Stainless steel
Emerald: Tungstensteel

**Pull request merged**
