### PR TITLE
Stainless

### PR DESCRIPTION
**Pull request by Angel-Abaddon**
rectifying firma and greg stainless steel to allow the crafting of the vat, jarring station, and max teir green house

### CODE REVIEW

**Comment by screret** [comment]
no. we're NOT having 2 different stainless steels. no chance.

**Comment by Angel-Abaddon** [comment]
I mean it was renamed (even in the book) to help avoid any confusion

**Comment by screret** [comment]
you do realise that chromium is already a thing that exists?

**Comment by Angel-Abaddon** [comment]
chromite to make chromium to make chrome. it made sense to me but we can change the name if thats a big deal?

**Pull request closed without merging**
